### ISSUE TITLE
Add test 

### ISSUE THREAD

**Issue by Jolg42** [prisma/engines-wrapper#411]
https://github.com/prisma/engines-wrapper/tree/main/packages/engines-version doesn't have any test

It would be better to have some test, so we can safely merge Renovate PRs like https://github.com/prisma/engines-wrapper/pull/240

**Comment by aqrln** [comment]
(Corollary: whichever contrived test we may add to https://github.com/prisma/engines-wrapper/tree/main/packages/engines-version, it probably won't help us much be able to merge Renovate PRs with confidence since it's not the code that will likely break if something is wrong with the updated dependencies)

**Comment by Jolg42** [comment]
Since https://github.com/prisma/engines-wrapper/pull/441 we have a build action which will let us know if TS compilation fails.

**Comment by Jolg42** [comment]
I think we can close this now
